"""Import every model so SQLAlchemy metadata (and Alembic) sees all tables."""

from app.models.billing import (
    Payment,
    PaymentProviderName,
    PaymentStatus,
    PlanCode,
    Subscription,
    SubscriptionPlan,
    SubscriptionStatus,
    UsageRecord,
)
from app.models.decision import (
    Decision,
    DecisionHistory,
    DecisionInsight,
    DecisionScenario,
    DecisionStatus,
    OutcomeRating,
    WhatIfExperiment,
)
from app.models.messaging import (
    CallSession,
    CallStatus,
    Conversation,
    ConversationMember,
    MediaFile,
    Message,
    MessageAttachment,
    MessageType,
    Notification,
    NotificationType,
    VoiceNote,
)
from app.models.social import (
    Block,
    BusinessProfile,
    Comment,
    FriendRequest,
    FriendRequestStatus,
    Match,
    PortfolioItem,
    Referral,
    Report,
    ReportStatus,
    SharedPost,
    UserInvite,
)
from app.models.user import AuditLog, Profile, Session, TermsAcceptance, User, UserRole, Visibility

__all__ = [
    "AuditLog",
    "Block",
    "BusinessProfile",
    "CallSession",
    "CallStatus",
    "Comment",
    "Conversation",
    "ConversationMember",
    "Decision",
    "DecisionHistory",
    "DecisionInsight",
    "DecisionScenario",
    "DecisionStatus",
    "FriendRequest",
    "FriendRequestStatus",
    "Match",
    "MediaFile",
    "Message",
    "MessageAttachment",
    "MessageType",
    "Notification",
    "NotificationType",
    "OutcomeRating",
    "Payment",
    "PaymentProviderName",
    "PaymentStatus",
    "PlanCode",
    "PortfolioItem",
    "Profile",
    "Referral",
    "Report",
    "ReportStatus",
    "Session",
    "SharedPost",
    "Subscription",
    "SubscriptionPlan",
    "SubscriptionStatus",
    "TermsAcceptance",
    "UsageRecord",
    "User",
    "UserInvite",
    "UserRole",
    "Visibility",
    "VoiceNote",
    "WhatIfExperiment",
]
